Add internal dependencies to run_terraform

diff --git a/.github/actions/run_terraform/action.yaml b/.github/actions/run_terraform/action.yaml
--- a/.github/actions/run_terraform/action.yaml
+++ b/.github/actions/run_terraform/action.yaml
@@ -42,13 +42,15 @@ runs:
         git checkout origin/main -- terraform/ || true
 
     - name: Terraform Init
+      id: init
       working-directory: ./terraform
       shell: bash
       run: |
         terraform init -upgrade 
 
     - name: Terraform Plan
-      id: terraform
+      id: plan
+      needs: init
       working-directory: ./terraform
       shell: bash
       run: |
@@ -75,7 +77,8 @@ runs:
         TF_LOG: DEBUG
 
     - name: Terraform Apply
-      id: terraform
+      id: apply
+      needs: [init, plan]
       shell: bash
       working-directory: ./terraform
       run: |
@@ -104,8 +107,19 @@ runs:
         TF_VAR_digital_ocean_ssh_private_key: ${{ inputs.digital_ocean_ssh_private_key }}
         TF_LOG: DEBUG
 
+    - name: Check for Terraform Errors
+      id: check_errors
+      needs: apply
+      shell: bash
+      run: |
+        if [ "${{ steps.apply.outputs.terraform_error }}" == "true" ]; then
+          echo "Terraform operations encountered errors"
+          exit 1
+        fi
+
     - name: Check for State File Changes
       id: check_state_changes
+      needs: apply
       shell: bash
       run: |
         git fetch origin main
@@ -116,6 +130,8 @@ runs:
         fi
 
     - name: Commit and push changes
+      id: commit
+      needs: check_state_changes
       shell: bash
       run: |
         git config --global user.name "github-actions"
@@ -126,12 +142,4 @@ runs:
         else
           git commit -m "Save Terraform state, lock file and domain list"
           git push https://${{ inputs.GH_PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git main
-        fi
-
-    - name: Check for Terraform Errors
-      shell: bash
-      run: |
-        if [ "${{ steps.terraform.outputs.terraform_error }}" == "true" ]; then
-          echo "Terraform operations encountered errors"
-          exit 1
         fi
